### ISSUE TITLE
Can't use Yarn with current dependency on matice

### ISSUE THREAD

**Issue by sebastiaanspeck** [RocketC31/budget#58]
Hello,

Could you explain to me what the biggest difference is between [the original matice](https://github.com/GENL/matice/) and [yours](https://github.com/RocketC31/matice)?

I'm having problems to use yours, since I can't access your repo to pull:
```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I ended up fixing this issue by using `yarn add matice`

**Comment by RocketC31** [comment]
Hi
It was only for dependecies updates because package was not update with his dependecies

if now it’s okey we can re set the original repository for matice. I have done it temporary only for that

**Comment by sebastiaanspeck** [comment]
Hi, thanks for the quick response. I don't know what the (biggest) problems were with the out-of-date dependencies, but in normal use I don't feel any effect of the original matice.

**Comment by RocketC31** [comment]
No biggest problem. Github bot security show alert for dependencies (js) issues. But cant update so warning stay here continually… 
But no problem if you think it was not a biggest problem we can go back to the original repo.

**Comment by sebastiaanspeck** [comment]
Or maybe, if we want to keep our dependencies up to date, we need to fix the errors is get:
```
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/RocketC31/matice.git
Directory: /var/www/html
Output:
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by sebastiaanspeck** [comment]
I found out that using `npm install` can handle it "correctly":
```
$ npm install
npm WARN skipping integrity check for git dependency ssh://git@github.com/RocketC31/matice.git
```

**Comment by sebastiaanspeck** [comment]
I was using yarn because nom gave me some problems at first, but I was mixing up now.
After I reverted the package-lock.json to its original state and throw away my node_modules, I could use `npm install` correctly. The only thing is that it replaces the name on line 2 from "budget" to "html"

**Comment by RocketC31** [comment]
Thanks for your feeback, i dont use yarn, i will see shortly it for make it working with github repo

Strange thing your rename, i make the same thing and it's the good name on line 2
