### ISSUE TITLE
Create transaction table and remove earning and spending

### ISSUE THREAD

**Issue by RocketC31** [RocketC31/budget#69]
Like earning and spending are similary. It will be good thing to merge the two one on only one table : transaction

- Négative value will be spending
- Positive value will be earning
- Like that, the spending can have tag too
- That will simplify the logic of index controller for transactions

**Comment by sebastiaanspeck** [comment]
Maybe first make an overview how to handle this merge-operation by answering the questions down below.
 
- How do cooperate with existing earnings/spendings
- Do we want to merge the Controllers/Repositories for earnings/spendings
- How do we recognise earnings vs spendings in the Transaction-table? By using a field (preferably an enumerator) `type` or by determining it via the `amount`-field?

**Comment by RocketC31** [comment]
Thanks for your feed back, in my opinion : 

- We can create a new table named "transactions" with the same columns as spendings (the two one are simily, just tag_id is missing in earning) and make a copy of earnings and spendings into it. After that, remove the earnings/spendings table. All of that on a migration.
- I think it will be good to merge the two one yes, or rework on it for simplify. On place where we try to find earnings only or spendings only, we have just to add filter on amount negative or positive
- I have spoiled on last point, i think the more simple is to determining it via amount no ? It's explicit, you can't earn negative amount ? i dont see case when type column will be necessary, but i can miss a usecase maybe you have an example ?

What is your opinion ?

**Comment by sebastiaanspeck** [comment]
Your answers seem okay to me. 
Regarding the last question, I haven't checked how the system corporates when filling in negative amounts right now, but for code readability I thought that using a type-column makes it easier to filter instead of determining it via the amount. You store the type explicitly.

**Comment by RocketC31** [comment]
We can make like that if it's more explicit

And like you suggest, we can use a enumeration. Or... maybe tinyint ? 0 for earning, 1 for spending and constant in code explain that ?

```PHP
class TransactionRepository
{
  const TYPE_EARNING = 0;
  const TYPE_SPENDING = 1;

  public function fakeMethodForFetchSpendings()
  {
    //it's an example
    return $query->where("type", static::TYPE_SPENDING)
  }
}
```

Enum is more readble for users in database. But if i'm not talking nonsense i thing it's better for performance to use tinyint no ?

**Comment by sebastiaanspeck** [comment]
Tinyint looks okay to me. I don't know what the performance penalty will be when using enum over tinyint, but logically thinking, enum will definitely use more memory so it might as well be slower

**Comment by RocketC31** [comment]
Exactly, me too i don't know where it's better to use tinyint but for memory it's sure tinyint will be better
