### ISSUE TITLE
No flags shown anymore when selecting language

### ISSUE THREAD

**Issue by sebastiaanspeck** [RocketC31/budget#70]
<img width="423" alt="image" src="https://user-images.githubusercontent.com/12570668/202227802-596e6f1c-90c5-486c-b1c0-ca05d824033c.png">

The twemoji-flags.css is deleted in https://github.com/RocketC31/budget/commit/cccf7d11a7e2f8ef7e00148949d66bd8589a3500 but a reference still exists: `<link rel="stylesheet" href="/twemoji-flags.css" />` in `resources\views\app.blade.php`

**Comment by RocketC31** [comment]
Woops sorry, i have thinking it was not used anymore. The absence of flag does not bother me that said.
What do you prefer you ?

**Comment by sebastiaanspeck** [comment]
Also remove `<i class="twf twf-s twf-' . $flag . '"></i> '` in `SettingsController`

**Comment by RocketC31** [comment]
Thanks @sebastiaanspeck !
