### ISSUE TITLE
After running `php artisan budget:install` my `yarn.lock` is updated

### ISSUE THREAD

**Issue by sebastiaanspeck** [RocketC31/budget#73]
See https://github.com/sebastiaanspeck/budget/commit/0d5aaef08845224d242e4ca72b30bee1a9699cb5 for the contents. Maybe we/you need to update the dependencies (and update composer as well)?

**Comment by RocketC31** [comment]
Hmm... The yarn.lock file isn't supposed to stay locked until we perform a yarn update? Like with npm?
I have the impression that it re writes following a yarn install in BudgetInstall.php

**Comment by sebastiaanspeck** [comment]
After running `yarn install` it doesn't update, but when using `npm install` it does update

**Comment by RocketC31** [comment]
It's seem to be a know issue https://github.com/npm/cli/issues/5126 on npm

**Comment by sebastiaanspeck** [comment]
So the fix for now is to use `yarn` over `npm`

**Comment by RocketC31** [comment]
Someone say 
> I mean, the workaround is just to restore the file with git restore yarn.lock after npm is run, but it gets boring.

We can maybe add on budgetinstall this restore if we select npm as package manager ?

**Comment by sebastiaanspeck** [comment]
Sounds like a good idea
