### ISSUE TITLE
Ideas-table

### ISSUE THREAD

**Issue by sebastiaanspeck** [RocketC31/budget#78]
In the original Budget, there is an option to suggest ideas, which will be inserted in the Ideas-table.

In [this commit](https://github.com/RocketC31/budget/blob/e9bb8fbe0ef2484e31ef8f6084835efb67649341/routes/web.php) you removed the routes for this. In my opinion the table itself can be removed, including the IdeaController and Model.

**Comment by RocketC31** [comment]
Yes i have remove it because i think github can be a place for idea. I have only remove route firstly. For permit to me to rollback if finally we prefer to have a place in the app to add idea. 

What do you think about ? If like me you think it's not usefull, we can in effect remove it everywhere

**Comment by sebastiaanspeck** [comment]
In my opinion it can be removed at all. GitHub seems okay for issue tracking

**Comment by RocketC31** [comment]
Ok thanks for you feedback i can do that tomorrow before start #69
